import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

#decorations = "None"
#opacity = 0.9
#blur = true
startup_mode = "Fullscreen"

[font]
normal.family = "Hack Nerd Font"
size = 16 

# For some reason, C-6 in neovim when using tmux was not switching
# to the previous buffer. This fixes that.
[[keyboard.bindings]]
key = "Key6"
mods = "Control"
chars = "\u001E"
