[metadata]
name = "sftp"
description = "Browse and connect to sftp servers"

[source]
command = "cat ~/.ssh_hosts | grep '^[A-z]' | sort | cut -d'|' -f1"
no_sort = true

[keybindings]
enter = "actions:open"

[actions.open]
description = "Connect"
command = 'eval $(sftp-get-command {})'
mode = "execute"
