[metadata]
name = "ssh"
description = "Browse and connect to ssh servers"

[source]
command = "cat ~/.ssh_hosts | grep '^[[:alpha:]]' | sort | cut -d'|' -f1"
no_sort = true

[keybindings]
enter = "actions:open"

[actions.open]
description = "Connect"
command = 'eval $(ssh-get-command {})'
mode = "execute"
