# Move windows within tiling layout
bind = $mainMod SHIFT, left,  movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up,    movewindow, u
bind = $mainMod SHIFT, down,  movewindow, d

# Screenshot
bind = $mainMod SHIFT, P, exec, grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png

# Application bindings
#bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bind = $mainMod, RETURN, exec, $terminal #bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"

bind = $mainMod SHIFT, B, exec, firefox #bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bind = $mainMod SHIFT, F, exec, $fileManager #bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bind = $mainMod SHIFT, O, exec, obsidian #bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
#bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
#bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
#bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
#bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
#bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
#bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
#bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
#bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
#bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
#bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
#bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bind = $mainMod SHIFT, G, exec, firefox "https://github.com" #bindd = SUPER SHIFT, G, Github, exec, omarchy-launch-webapp "https://github.com"
bind = $mainMod SHIFT, S, exec, firefox "https://app.slack.com/client/T6SPCTC8L/C08NT9310RE" #bindd = SUPER SHIFT, S, Slack, exec, omarchy-launch-webapp "https://app.slack.com/client/T6SPCTC8L/C08NT9310RE"
bind = $mainMod SHIFT, E, exec, firefox "https://gmail.com" #bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://gmail.com"
bind = $mainMod SHIFT, C, exec, firefox "https://calendar.google.com/calendar" #bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/calendar"
bind = $mainMod SHIFT, Y, exec, firefox "https://youtube.com/" #bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bind = $mainMod SHIFT, M, exec, firefox "https://meet.google.com" #bindd = SUPER SHIFT, M, Meet, exec, omarchy-launch-webapp "https://meet.google.com"
bind = $mainMod SHIFT, N, exec, firefox "https://notion.so/" #bindd = SUPER SHIFT, N, Notion, exec, omarchy-launch-webapp "https://notion.so/"


# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
