general {
    lock_cmd = pidof hyprlock || hyprlock   # don't spawn multiple hyprlock instances
    before_sleep_cmd = hyprlock             # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim screen after 4 minutes
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Turn off displays after 10 minutes
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
