# Make consistent with Omarchy
# Close windows
bindd = SUPER, W, Close window, killactive,
#bindd = CTRL ALT, DELETE, Close all windows, exec, omarchy-hyprland-window-close-all

# Control tiling
#bindd = SUPER, J, Toggle window split, layoutmsg, togglesplit # Not needed - already in hyprland.conf
#bindd = SUPER, P, Pseudo window, pseudo, # dwindle # Not needed - already in hyprland.conf
bindd = SUPER, T, Toggle window floating/tiling, togglefloating,
bindd = SUPER, F, Full screen, fullscreen, 0
#bindd = SUPER CTRL, F, Tiled full screen, fullscreenstate, 0 2 # Come back to this
bindd = SUPER ALT, F, Full width, fullscreen, 1
#bindd = SUPER, O, Pop window out (float & pin), exec, omarchy-hyprland-window-pop # Come back to this
#bindd = SUPER, L, Toggle workspace layout, exec, omarchy-hyprland-workspace-layout-toggle # Come back to this

# Move focus with SUPER + arrow keys
# bindd = SUPER, LEFT, Move window focus left, movefocus, l# Not needed - already in hyprland.conf
# bindd = SUPER, RIGHT, Move window focus right, movefocus, r# Not needed - already in hyprland.conf
# bindd = SUPER, UP, Move window focus up, movefocus, u# Not needed - already in hyprland.conf
# bindd = SUPER, DOWN, Move window focus down, movefocus, d# Not needed - already in hyprland.conf

# Switch workspaces with SUPER + [1-9; 0]# Not needed - already in hyprland.conf
#bindd = SUPER, code:10, Switch to workspace 1, workspace, 1
#bindd = SUPER, code:11, Switch to workspace 2, workspace, 2
#bindd = SUPER, code:12, Switch to workspace 3, workspace, 3
#bindd = SUPER, code:13, Switch to workspace 4, workspace, 4
#bindd = SUPER, code:14, Switch to workspace 5, workspace, 5
#bindd = SUPER, code:15, Switch to workspace 6, workspace, 6
#bindd = SUPER, code:16, Switch to workspace 7, workspace, 7
#bindd = SUPER, code:17, Switch to workspace 8, workspace, 8
#bindd = SUPER, code:18, Switch to workspace 9, workspace, 9
#bindd = SUPER, code:19, Switch to workspace 10, workspace, 10

# Move active window to a workspace with SUPER + SHIFT + [1-9; 0]# Not needed - already in hyprland.conf
#bindd = SUPER SHIFT, code:10, Move window to workspace 1, movetoworkspace, 1
#bindd = SUPER SHIFT, code:11, Move window to workspace 2, movetoworkspace, 2
#bindd = SUPER SHIFT, code:12, Move window to workspace 3, movetoworkspace, 3
#bindd = SUPER SHIFT, code:13, Move window to workspace 4, movetoworkspace, 4
#bindd = SUPER SHIFT, code:14, Move window to workspace 5, movetoworkspace, 5
#bindd = SUPER SHIFT, code:15, Move window to workspace 6, movetoworkspace, 6
#bindd = SUPER SHIFT, code:16, Move window to workspace 7, movetoworkspace, 7
#bindd = SUPER SHIFT, code:17, Move window to workspace 8, movetoworkspace, 8
#bindd = SUPER SHIFT, code:18, Move window to workspace 9, movetoworkspace, 9
#bindd = SUPER SHIFT, code:19, Move window to workspace 10, movetoworkspace, 10

# Control scratchpad# Not needed - already in hyprland.conf
#bindd = SUPER, S, Toggle scratchpad, togglespecialworkspace, scratchpad
